[package]
name = "vrc-get"
version = "1.8.2-beta.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

description = "Open Source command line client of VRChat Package Manager."
readme = "README.md"
keywords = ["vpm", "package-manager"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle = "1.0.7"
clap = { version = "4.5.8", features = ["derive"] }
clap_complete = "4.5.7"
color-print = "0.3.6"
env_logger = "0.11.3"
indexmap = { version = "2.2.6", features = ["serde"] }
itertools = "0.13.0"
log = "0.4.22"
reqwest = { version = "0.12.5", default-features = false }
serde = { version = "1.0.204", features = ["derive", "rc"] }
serde_json = { version = "1.0.120", features = ["preserve_order"] }
tokio = { version = "1.38.1", features = ["rt-multi-thread", "macros", "fs"] }

[dependencies.vrc-get-vpm]
version = "0.0.13-beta.0"
path = "../vrc-get-vpm"
features = ["tokio"]
default-features = false

[build-dependencies]
home = "0.5.9"

[features]
default = ["rustls"]
native-tls = ["vrc-get-vpm/native-tls"]
rustls = ["vrc-get-vpm/rustls"]

experimental-vcc = ["vrc-get-vpm/experimental-project-management", "vrc-get-vpm/experimental-unity-management"]

# binstall support
[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }-{ name }{ binary-ext }"
pkg-fmt = "bin"
